config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  
  resources :tasks
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to '/'
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
   private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in
    before_action :correct_user, only: [:show, :edit, :update, :destroy]
    
    def index
        @tasks = current_user.tasks.order(id: :desc)
    end
    
    def show
    end
    
    def new
        @task = current_user.tasks.build
    end
    
    def create
        @task = current_user.tasks.build(task_params)
        
        if @task.save
            flash[:success] = 'Taskが正常に投稿されました'
            redirect_to task_url(@task)
        else
            flash.now[:danger] = 'Taskが投稿されませんでした'
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @task.update(task_params)
            flash[:success] = 'Taskが正常に更新されました'
            redirect_to task_url(@task)
        else
            flash.now[:danger] = 'Taskが更新されませんでした'
            render :edit
        end
    end
    
    def destroy
        @task.destroy
        
        flash[:success] = 'Taskは正常に削除されました'
        redirect_to tasks_url
    end
    
    private
    
    #Strong Parameter
    def task_params
        params.require(:task).permit(:content, :status)
    end
    
    def correct_user
        @task = current_user.tasks.find_by(id: params[:id])
        
        unless @task
            redirect_to '/'
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to '/'
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash_messages' %>
    
    <%= yield %>
    <% if logged_in? %>
      <%= link_to 'ログアウト', logout_path, method: :delete %>
    <% end %>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if task.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this message from being saved:</h2>
        
        <ul>
            <% task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_with(model: task, local: true) do |f| %>
    <%= f.label :content, 'タスク内容' %>
    <%= f.text_field :content, placeholder: 'taskを入力' %>
    
    <%= f.label :status, 'ステータス' %>
    <%= f.text_field :status %>
    
    <%= f.submit '投稿' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>id：<%= @task.id %>のタスク編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<% if logged_in? %>

  <h1><%= @current_user.name %>のタスク一覧</h1>
  
  <% @current_user.tasks.each do |task| %>
    <li><%= link_to task.id, task_path(task) %>：<%= task.content %> &gt; <%= task.status %></li>
  <% end %>

  <%= link_to '新規タスクの作成', new_task_path %>
  
<% else %>
  <%= link_to 'ログイン', login_path %>
  <%= link_to '新規登録', signup_path %>
<% end %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id：<%= @task.id %>のタスク詳細ページ</h1>

<p>内容：<%= @task.content %></p>
<p>ステータス：<%= @task.status %></p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: {confirm: '本当に削除してよろしいですか？'} %>

app/views/users/new.html.erb
<h1>ユーザー新規作成</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this message from being saved:</h2>
        
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name %>
  
  <%= f.label :email, 'Email' %>
  <%= f.email_field :email %>
  
  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation, 'Confirmation' %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit '登録' %>
  
<% end %>

<p><%= link_to 'ログイン', login_path %></p>